name: Terraform-AWS-Deploy
run-name: Deploy infrastructure on AWS 🚀

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO #?
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check for Deploy Flag
      run: |
        if [ ! -f deploy.flag ] || [ "$(cat deploy.flag)" != "true" ]; then
          echo "Deployment flag not set to true. Exiting..."
          exit 1
        fi

    - name: Terraform Init
      run: terraform init 
    
    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Apply Terraform
      if: steps.plan.outcome == 'success'
      run: terraform apply -auto-approve -input=false
      
  

        


